<?php

use Drupal\Core\Entity\EntityInterface;

function du_tuition_calculator_entity_view(array &$build, EntityInterface $entity, $view_mode, $langcode) {
  if ($entity->getEntityTypeId() === 'paragraph' && $entity->bundle() === 'du_tuition_calculator') {
    // Build the calculator form.
    $build['calculator'] = \Drupal::formBuilder()
      ->getForm(\Drupal\du_tuition_calculator\Form\Calculator::class);

    $build['#attributes']['class'][] = 'paragraph--type--du-tuition-calculator';
  }
}
